version: 0.2  
phases:
  install:
    runtime-versions:
      java: openjdk11
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the JAR file...
      - mvn package
artifacts: 
  files:
      - target/my-app-1.0-RELEASE.jar
  discard-paths: yes 
