version: 0.2  
phases:
  install:
    runtime-versions:
      java: openjdk11
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the JAR file...
      - mvn sonar:sonar -Dsonar.login=ca60797bbd859cf11d5e3cfd6efce06ea86cd87b -Dsonar.host.url=http://63.33.207.154:9000
      - mvn package
artifacts: 
  files:
      - target/my-app-1.0-RELEASE.jar
  discard-paths: yes